-- Layout Gráfica

USE moper_dsv;


IF EXISTS(SELECT LAYOUTTYPE_ID FROM LAYOUTTYPE WHERE NAME = 'GRAFICA')
        BEGIN
                DECLARE @LAYOUTTYPE_ID NUMERIC = (SELECT LAYOUTTYPE_ID FROM LAYOUTTYPE WHERE NAME = 'GRAFICA');
                DELETE FROM LAYOUT WHERE LAYOUTTYPE_ID = @LAYOUTTYPE_ID
                DELETE FROM LAYOUTVERSION WHERE LAYOUTVERSION_ID = @LAYOUTTYPE_ID
                DELETE FROM LAYOUTTYPE WHERE NAME = 'GRAFICA'
        END
GO


IF EXISTS(SELECT * FROM ROWTYPE)
        DELETE FROM ROWTYPE
GO

SET IDENTITY_INSERT ROWTYPE ON 

INSERT INTO ROWTYPE(ROWTYPE_ID, DESCR)VALUES(1, 'HEADER');
GO
INSERT INTO ROWTYPE(ROWTYPE_ID, DESCR)VALUES(2, 'DETAIL');
GO
INSERT INTO ROWTYPE(ROWTYPE_ID, DESCR)VALUES(3, 'TRAILLER');
GO
SET IDENTITY_INSERT ROWTYPE OFF
GO


INSERT INTO LAYOUTTYPE(NAME, DESCR)VALUES('GRAFICA', 'LAYOUT EXTRACAO GRAFICA');
DECLARE @LAYOUTTYPEID  NUMERIC = @@IDENTITY

INSERT INTO LAYOUTVERSION(DESCR, GENERATEDATE, VERSIONLAYOUT, LAYOUTTYPE_ID)VALUES('INIT', GETDATE(), 0, @LAYOUTTYPEID);
DECLARE @LAYOUTVERSIONID  NUMERIC = @@IDENTITY


INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Identificação da seção' , ' Constante 0 ', 1 , 1 , 1 , 1 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Identificação de tipo de arquivo' , ' Constante 1 - Remessa
Constante 2 - Retorno ', 2 , 3 , 2 , 2 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Origem do arquivo' , ' CARDIF ', 4 , 53 , 50 , 3 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Destino do arquivo' , ' METASOLUTIONS ', 54 , 103 , 50 , 4 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Arquivo' , ' Nome do Arquivo (Upload) ', 104 , 128 , 25 , 5 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Data do movimento' , ' Data da movimentação do arquivo (formato AAAAMMDD)   ', 129 , 136 , 8 , 6 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Número da remessa' , ' Número sequencial da remessa, ex: 000000001 ', 137 , 146 , 10 , 7 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Filler' , ' Brancos ', 147 , 2500 , 2354 , 8 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Identificação da seção' , ' Constante 1 ', 1 , 1 , 1 , 1 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Tipo de Impressão' , ' 1 - 1ª Impressão
2 - Reimpressão ', 2 , 2 , 1 , 2 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Apólice' , ' Número da Apólice ', 3 , 12 , 10 , 3 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Boneco' , ' Nome do Boneco ', 13 , 22 , 10 , 4 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Nome' , ' Nome do Segurado ', 23 , 72 , 50 , 5 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CPF' , ' CPF do Segurado ', 73 , 83 , 11 , 6 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Data de Nascimento' , ' (Formato AAAAMMDD)   ', 84 , 91 , 8 , 7 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Sexo' , ' F - Feminino/ M - Masculino ', 92 , 92 , 1 , 8 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Endereço' , ' Logradouro e Número ', 93 , 142 , 50 , 9 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Complemento' , ' Complemento do Endereço ', 143 , 157 , 15 , 10 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Bairro' , ' Bairro do Segurado ', 158 , 182 , 25 , 11 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cidade' , ' Cidade do Segurado ', 183 , 207 , 25 , 12 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Estado' , ' Estado do Segurado ', 208 , 209 , 2 , 13 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CEP' , ' Ex: 04855360 ', 210 , 217 , 8 , 14 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('E-mail' , ' E-mail do Segurado ', 218 , 242 , 25 , 15 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Contrato' , ' Nº do Contrato no Parceiro ', 243 , 272 , 30 , 16 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Certificado' , ' Número do Certificado ', 273 , 287 , 15 , 17 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Numero Certificado Acsele' , ' Numero Certificado Acsele ', 288 , 327 , 40 , 18 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Data Adesão' , ' (Formato AAAAMMDD)   ', 328 , 335 , 8 , 19 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Vigência início' , ' Início de Vigência do Seguro
(Formato AAAAMMDD) ', 336 , 343 , 8 , 20 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Vigência Fim' , ' Fim de Vigência do Seguro
(Formato AAAAMMDD) ', 344 , 351 , 8 , 21 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Periodicidade' , ' Periodicidade do Prêmio
Ex: Mensal, Anual, Único ', 352 , 366 , 15 , 22 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Mensal' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 367 , 376 , 10 , 23 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Total' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 377 , 386 , 10 , 24 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('IOF' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 387 , 396 , 10 , 25 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Plano/Cobertura Contratada' , ' Plano Contratado ', 397 , 421 , 25 , 26 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 1' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 422 , 431 , 10 , 27 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 1' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 432 , 441 , 10 , 28 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 2' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 442 , 451 , 10 , 29 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 2' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 452 , 461 , 10 , 30 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 3' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 462 , 471 , 10 , 31 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 3' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 472 , 481 , 10 , 32 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 4' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 482 , 491 , 10 , 33 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 4' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 492 , 501 , 10 , 34 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 5' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 502 , 511 , 10 , 35 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 5' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 512 , 521 , 10 , 36 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 6' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 522 , 531 , 10 , 37 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 6' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 532 , 541 , 10 , 38 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 7' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 542 , 551 , 10 , 39 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 7' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 552 , 561 , 10 , 40 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 8' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 562 , 571 , 10 , 41 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 8' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 572 , 581 , 10 , 42 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 9' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 582 , 591 , 10 , 43 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 9' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 592 , 601 , 10 , 44 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Prêmio Cobertura 10' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 602 , 611 , 10 , 45 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura 10' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 612 , 621 , 10 , 46 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura Percentual 1' , ' LMI Percentual ', 622 , 625 , 4 , 47 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Cobertura Percentual 2' , ' LMI Percentual ', 626 , 629 , 4 , 48 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Parcelas 1' , ' Quantidade de Parcelas/ Utilização ', 630 , 632 , 3 , 49 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Parcelas 2' , ' Quantidade de Parcelas/ Utilização ', 633 , 635 , 3 , 50 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Parcelas 3' , ' Quantidade de Parcelas/ Utilização ', 636 , 638 , 3 , 51 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Parcelas 4' , ' Quantidade de Parcelas/ Utilização ', 639 , 641 , 3 , 52 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('LMI Parcelas 5' , ' Quantidade de Parcelas/ Utilização ', 642 , 644 , 3 , 53 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário 1' , ' Nome do Beneficiário 1 ', 645 , 694 , 50 , 54 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário % Participação 1' , ' Percentual - Participação do Benefíciario 1 ', 695 , 698 , 4 , 55 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário  Data Nascimento 1' , ' (Formato AAAAMMDD)   ', 699 , 706 , 8 , 56 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário Grau Parentesco 1' , ' Ex: Cônjuge, Filho, Neto, etc. ', 707 , 716 , 10 , 57 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário 2' , ' Nome do Beneficiário 2 ', 717 , 766 , 50 , 58 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário % Participação 2' , ' Percentual - Participação do Benefíciario 2 ', 767 , 770 , 4 , 59 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário  Data Nascimento 2' , ' (Formato AAAAMMDD)   ', 771 , 778 , 8 , 60 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário Grau Parentesco 2' , ' Ex: Cônjuge, Filho, Neto, etc. ', 779 , 788 , 10 , 61 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário 3' , ' Nome do Beneficiário 3 ', 789 , 838 , 50 , 62 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário % Participação 3' , ' Percentual - Participação do Benefíciario 3 ', 839 , 842 , 4 , 63 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário  Data Nascimento 3' , ' (Formato AAAAMMDD)   ', 843 , 850 , 8 , 64 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário Grau Parentesco 3' , ' Ex: Cônjuge, Filho, Neto, etc. ', 851 , 860 , 10 , 65 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário 4' , ' Nome do Beneficiário 4 ', 861 , 910 , 50 , 66 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário % Participação 4' , ' Percentual - Participação do Benefíciario 4 ', 911 , 914 , 4 , 67 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário  Data Nascimento 4' , ' (Formato AAAAMMDD)   ', 915 , 922 , 8 , 68 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário Grau Parentesco 4' , ' Ex: Cônjuge, Filho, Neto, etc. ', 923 , 932 , 10 , 69 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário 5' , ' Nome do Beneficiário 5 ', 933 , 982 , 50 , 70 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário % Participação 5' , ' Percentual - Participação do Benefíciario 5 ', 983 , 986 , 4 , 71 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário  Data Nascimento 5' , ' (Formato AAAAMMDD)   ', 987 , 994 , 8 , 72 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Beneficiário Grau Parentesco 5' , ' Ex: Cônjuge, Filho, Neto, etc. ', 995 , 1009 , 15 , 73 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Apólice Variável' , ' Nº de Apólice (caso seja variável) ', 1010 , 1034 , 25 , 74 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cap Periodicidade' , ' Ex: Semanal, Mensal ', 1035 , 1044 , 10 , 75 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cap Vigência' , ' Ex: 1 mês, 12 meses, acompanha a vigência do Certificado de Seguro ', 1045 , 1094 , 50 , 76 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cap Valor Bruto' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 1095 , 1104 , 10 , 77 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cap IR' , ' Percentual de Desconto de IR ', 1105 , 1108 , 4 , 78 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cap Valor Líquido' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 1109 , 1118 , 10 , 79 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cap Número da Sorte' , ' Ex: 12345 ', 1119 , 1123 , 5 , 80 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Assistência Plano' , ' Plano de Assistência Contratado ', 1124 , 1148 , 25 , 81 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Marca' , ' Marca do veículo ', 1149 , 1163 , 15 , 82 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Modelo' , ' Modelo do veículo ', 1164 , 1178 , 15 , 83 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Ano/Modelo' , ' Ano / Modelo do Veículo
(Formato AAAA)  ', 1179 , 1182 , 4 , 84 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Veículo 0km' , ' Informar se o Veículo é 0 KM 
Sim ou Não ', 1183 , 1185 , 3 , 85 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Chassi' , ' Número do Chassi do Veículo ', 1186 , 1205 , 20 , 86 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Placa' , ' Placa do Veículo ', 1206 , 1212 , 7 , 87 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Renavan' , ' Renavan do Veículo ', 1213 , 1232 , 20 , 88 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cor' , ' Cor do Veículo ', 1233 , 1257 , 25 , 89 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Combustível' , ' Tipo de Combustível
Ex: Gasolina, Álcool, Flex, Diesel ', 1258 , 1272 , 15 , 90 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Código Referencia' , ' Código de referência FIPE ou MOLICAR, zeros a esquerda, sem pontos ou vírgulas ', 1273 , 1282 , 10 , 91 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Região Circulação' , ' Região Principal de Circulação do Veículo ', 1283 , 1312 , 30 , 92 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Nº Cartão' , ' Nº do Cartão Segurado ', 1313 , 1337 , 25 , 93 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Valor Financiado' , ' Zeros a esquerda, sendo duas casas decimais sem pontos ou virgulas ', 1338 , 1347 , 10 , 94 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Código Produto' , ' Código do Produto Segurado ', 1348 , 1372 , 25 , 95 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Marca Produto' , ' Marca do Produto Segurado ', 1373 , 1397 , 25 , 96 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Modelo Produto' , ' Modelo do Produto Segurado ', 1398 , 1422 , 25 , 97 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Descrição Produto' , ' Descrição do Produto Segurado ', 1423 , 1447 , 25 , 98 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Nº de Série ou Hexa' , ' Nº de Série do Produto Segurado ', 1448 , 1472 , 25 , 99 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Quantidade Produto' , ' Quantidade do Produto Segurado ', 1473 , 1475 , 3 , 100 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Garantia Fabricante Inicio' , ' Inicio de Garantia do Fabricante
(Formato AAAAMMDD) ', 1476 , 1483 , 8 , 101 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Garantia Fabricante Fim' , ' Fim de Garantia do Fabricante
(Formato AAAAMMDD) ', 1484 , 1491 , 8 , 102 , 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Vigência Garantia Fabricante' , ' Ex: 90 dias, 12 meses, 24 meses ', 1492 , 1506 , 15 , 103 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Endereço de Risco' , ' Logradouro e Número do Endereço de Risco ', 1507 , 1556 , 50 , 104 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Complemento Risco' , ' Complemento do Endereço de Risco ', 1557 , 1571 , 15 , 105 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Bairro Risco' , ' Bairro do Endereço de Risco ', 1572 , 1596 , 25 , 106 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cidade Risco' , ' Cidade do Endereço de Risco ', 1597 , 1621 , 25 , 107 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Estado Risco' , ' Estado do Endereço de Risco ', 1622 , 1646 , 25 , 108 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CEP Risco' , ' Ex: 04855360 ', 1647 , 1654 , 8 , 109 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Estipulante' , ' Razão Social do Estipulante ', 1655 , 1704 , 50 , 110 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CNPJ Estipulante' , ' CNPJ do Estipulante ', 1705 , 1718 , 14 , 111 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Pro-Labore %' , ' Percentual de Pro-labore do Estipulante ', 1719 , 1722 , 4 , 112 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Pro-Labore R$' , ' Valor de Pro-labore do Estipulante ', 1723 , 1732 , 10 , 113 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Subestipulante 1' , ' Razão Social do Subestipulante 1 ', 1733 , 1782 , 50 , 114 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CNPJ Subestipulante 1' , ' CNPJ do Subestipulante 1 ', 1783 , 1797 , 15 , 115 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Pro-Labore %' , ' Percentual de Pro-labore do Subestipulante 1 ', 1798 , 1801 , 4 , 116 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Pro-Labore R$' , ' Valor de Pro-labore do Subestipulante 1 ', 1802 , 1811 , 10 , 117 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Subestipulante 2' , ' Razão Social do Subestipulante 2 ', 1812 , 1861 , 50 , 118 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CNPJ Subestipulante 2' , ' CNPJ do Subestipulante 2 ', 1862 , 1876 , 15 , 119 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Pro-Labore %' , ' Percentual de Pro-labore do Subestipulante 2 ', 1877 , 1880 , 4 , 120 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Pro-Labore R$' , ' Valor de Pro-labore do Subestipulante 2 ', 1881 , 1890 , 10 , 121 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Cosseguradora' , ' Razão Social da Cosseguradora ', 1891 , 1940 , 50 , 122 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CNPJ' , ' CNPJ da Cosseguradora ', 1941 , 1954 , 14 , 123 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Participação % Seguradora' , ' Percentual de Participação da Seguradora ', 1955 , 1958 , 4 , 124 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Participação % Cosseguradora' , ' Percentual de Participação da Cosseguradora ', 1959 , 1962 , 4 , 125 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Corretor' , ' Nome do Corretor de Seguros ', 1963 , 2012 , 50 , 126 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CPF/CNPJ Corretor' , ' CPF/CNPJ do Corretor ', 2013 , 2026 , 14 , 127 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Registro SUSEP Corretor' , ' Nº de Registro do Corretor na Susep ', 2027 , 2041 , 15 , 128 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Endereço Corretor' , ' Logradouro e Nº do Corretor ', 2042 , 2091 , 50 , 129 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);


INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
        VALUES ('Complemento Corretor' , ' Complemento do Endereço do Corretor ', 2092 , 2106 , 15 , 130 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);



INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
        VALUES ('Bairro Corretor' , ' Bairro do Endereço do Corretor ', 2107 , 2131 , 25 , 131 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);


INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
        VALUES ('Cidade Corretor' , ' Cidade do Endereço do Corretor ', 2132 , 2156 , 25 , 132 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);


INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Estado Corretor' , ' Estado do Endereço do Corretor ', 2157 , 2181 , 25 , 133 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);


INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('CEP Corretor' , ' Ex: 04855360 ', 2182 , 2189 , 8 , 134 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('DDD Corretor' , ' DDD do Telefone do Corretor ', 2190 , 2191 , 2 , 135 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Telefone Corretor' , ' Telefone do Corretor ', 2192 , 2201 , 10 , 136 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Campo Texto 1' , ' Informações Adicionais - Texto ', 2202 , 2226 , 25 , 137 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Campo Texto 2' , ' Informações Adicionais - Texto ', 2227 , 2251 , 25 , 138 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Campo Texto 3' , ' Informações Adicionais - Texto ', 2252 , 2276 , 25 , 139 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Campo Número 1' , ' Informações Adicionais - Número ', 2277 , 2286 , 10 , 140 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Campo Número 2' , ' Informações Adicionais - Número ', 2287 , 2296 , 10 , 141 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Campo Número 3' , ' Informações Adicionais - Número ', 2297 , 2306 , 10 , 142 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Código Rejeição' , ' Motivo Rejeição - Arquivo Retorno ', 2307 , 2309 , 3 , 143 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Filler' , ' Brancos ', 2310 , 2500 , 191 , 144 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 2);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Identificação da seção' , ' Constante 9 ', 1 , 1 , 1 , 1 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 3);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Total registros' , ' Total de registros - 2 ', 2 , 9 , 8 , 2 , 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 3);
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
 VALUES ('Filler' , ' Brancos ', 10 , 2500 , 2491 , 3 , 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 3);
 GO
