-- Layout Gráfica

USE moper_dsv;

IF EXISTS(SELECT LAYOUTTYPE_ID FROM LAYOUTTYPE WHERE NAME = 'GRAFICA')
	BEGIN
		DECLARE @LAYOUTTYPE_ID NUMERIC = (SELECT LAYOUTTYPE_ID FROM LAYOUTTYPE WHERE NAME = 'GRAFICA');
		DELETE FROM LAYOUT WHERE LAYOUTTYPE_ID = @LAYOUTTYPE_ID
		DELETE FROM LAYOUTVERSION WHERE LAYOUTVERSION_ID = @LAYOUTTYPE_ID
		DELETE FROM LAYOUTTYPE WHERE NAME = 'GRAFICA'
	END
GO

INSERT INTO LAYOUTTYPE(NAME, DESCR)VALUES('GRAFICA', 'LAYOUT EXTRACAO GRAFICA');
DECLARE @LAYOUTTYPEID  NUMERIC = @@IDENTITY

INSERT INTO LAYOUTVERSION(DESCR, GENERATEDATE, VERSIONLAYOUT, LAYOUTTYPE_ID)VALUES('INIT', GETDATE(), 0, @LAYOUTTYPEID);
DECLARE @LAYOUTVERSIONID  NUMERIC = @@IDENTITY


INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Identificação da seção', 'Constante "0"', 1, 1 ,1,1, 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);

INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Identificação de tipo de arquivo', '"Constante ""1"" - Remessa Constante ""2"" - Retorno" ', 2, 3 ,2, 2, 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);

INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Origem do arquivo', 'CARDIF ', 4, 53 ,50, 3, 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);
	
INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Destino do arquivo', 'METASOLUTIONS ', 54, 103 ,50, 4, 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1); 

INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Arquivo', 'Nome do arquivo(UPLOAD) ', 104, 128 ,25, 5, 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);

INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Origem do arquivo', 'CARDIF ', 129, 136 ,8, 6, 'D', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);

INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Numero da remassa', '000000001 ', 137, 146 ,10, 7, 'N', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);

INSERT INTO LAYOUT(COLNAME, DESCR, BEGINFIELD, ENDFIELD, LENGHTFIELD, INDEXFIELD,TYPECOL, LAYOUTTYPE_ID, LAYOUTVERSION_ID, ROWTYPE_ID)
	VALUES ('Filler', 'Brancos ', 147, 2500 ,2354, 8, 'C', @LAYOUTTYPEID, @LAYOUTVERSIONID, 1);